version: "3"

services: 
    web:
        container_name: "node"
        restart: always
        build: .
        ports:
            - 4200:80
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 3000:3000
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_SERVER: database
        depends_on:
            - mongo

    mongo:
        container_name: "mymonguito"
        image: mongo
        ports:
            - 27017:27017  
        volumes: 
            - /data/dbase
          
    